---
title: "Animations and Interactivity"
output: html_document
---

# Isaac Bravo

## Problem 1

```{r problem_1_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK
library(tidyverse)

Category<-c("Alpha","Beta","Zeta")
City<-c("Hong Kong","London","Nairobi")

my_dat<-expand_grid(Category,City)

set.seed(84684)

my_dat$Value<-sample(1:10,9,replace=T)
```

```{r problem_1_solution,echo=FALSE,message=FALSE}

library(gganimate)
library(gifski)

###PUT YOUR ggplot figure with the appropriate gganimate functions here. It will compile in the html R Markdown report.

#ggplot(my_dat, aes(factor(Category), Value), fill=City) +
#  geom_bar(stat='identity') + 
#  facet_wrap(~City) +
#  transition_states(City) +
#  theme_bw() +
#  enter_fade() +
#  exit_fade()

ggplot(my_dat, aes(factor(Category), Value, fill=City)) +
  geom_bar(stat='identity') +
  transition_states(City) +
  theme_bw() +
  enter_fade() +
  exit_fade()

```

## Problem 2

```{r problem_2_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK

Response<-c("Energize","Amazing","Great")
set.seed(9819)
Energize<-tibble(Company=rep("Energize",100),Output=rnorm(100,50,20))
set.seed(9819)
Amazing<-tibble(Company=rep("Amazing",100),Output=rnorm(100,50,10))
set.seed(9819)
Great<-tibble(Company=rep("Great",100),Output=rnorm(100,40,5))

my_dat<-bind_rows(Energize,Amazing,Great)
```

```{r problem_2_solution,echo=FALSE,message=FALSE,warning=FALSE}

library(plotly)

###PUT YOUR ggplotly() figure here. It will compile in the R Markdown report.

p <- ggplot(my_dat, aes(x=factor(Company), y=Output,fill=Company))+
                 geom_boxplot()+
                  theme_bw()
fig <- ggplotly(p)
fig

```

## Problem 3

```{r problem_3_data,echo=FALSE,message=FALSE,warning=FALSE}

library(plotly)

Category<-seq(from=1,to=10)
Time<-seq(from=1,to=10)

dat3<-expand_grid(Category,Time)

set.seed(78957)
dat3$Quantity<-runif(100,0,10)
```


```{r problem_3_solution,echo=FALSE,message=FALSE,warning=FALSE}

library(plotly)

###PUT YOUR ggplotly() figure here. It will compile in the R Markdown report.

ggplotly( ggplot(dat3,aes(x=Time,y=Quantity,frame=Category))+
  geom_point(color="darkgreen")+ 
  geom_segment(aes(x=Time,xend=Time,y=0,yend=Quantity), color = "darkgreen")+
    labs(x="Category",y="Quantity") )

```